name: "Commander Tests/Build"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: commander

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

#  build:
#    runs-on: ubuntu-latest
#    needs: unit-test
#
#    steps:
